# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('role', models.CharField(choices=[('ADMIN', 'AD'), ('EMPLOYEE', 'EM'), ('GUEST', 'GU')], default='GUEST', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('v_token', models.CharField(max_length=20)),
                ('p_token', models.CharField(max_length=20)),
                ('p_expire_at', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
