# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSchedual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.datetime_safe.datetime.date)),
                ('chunk_id', models.IntegerField()),
                ('M_time_in', models.TimeField(blank=True)),
                ('M_time_out', models.TimeField(blank=True)),
                ('L_time_in', models.TimeField(blank=True)),
                ('L_time_out', models.TimeField(blank=True)),
                ('N_time_in', models.TimeField(blank=True)),
                ('N_time_out', models.TimeField(blank=True)),
                ('work_desc', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='created',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'AD'), ('EMPLOYEE', 'EM'), ('GUEST', 'GU')], default='GU', max_length=9),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timeschedual',
            unique_together=set([('user_id', 'work_date')]),
        ),
    ]
