# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_auto_20151221_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.datetime_safe.datetime.date)),
                ('chunk_id', models.IntegerField()),
                ('in_time', models.TimeField(blank=True)),
                ('out_time', models.TimeField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserValue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timesheetvalue',
            unique_together=set([('user_id', 'work_date', 'chunk_id')]),
        ),
    ]
