# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20151221_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSheetValue',
            new_name='TimeSheets',
        ),
    ]
